config/routes.rb
Rails.application.routes.draw do
  resources :profiles, except: [:index, :edit ]
  resource  :profile, only: [ :show, :edit]

  devise_for :users
  
  resources :listings
  resources :users, only: [] do
    resources :listings, only: [ :index ]
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :charges
  root 'pages#home'

  # get 'home', to: 'pages#home'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  has_many :listings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         mount_uploader :avatar, ImageUploader

        

  after_create do
    self.create_profile
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_item  
  
    def new
      
    end
    
    def create
      # Amount in cents
      @amount = @listing.cost
    
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
    
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Rails Stripe customer',
        :currency    => 'aud'
      )
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

    private
      def set_item
          @listing = Listing.find(params[:listing_id])
      end

     
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  # GET /listings
  # GET /listings.json
  def index
    if params[:user_id] and (params[:user_id].to_i == current_user.id) then
      @listings = current_user.listings
      @profiles = Profile.all
    else
      @listings = Listing.all
      @profiles = Profile.all
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show

  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user

    @current_user_listing = current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
        UserNotifierMailer.send_listing_email(@current_user_listing).deliver
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :description, :cost, :image, :user, :itinerary, :date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [ :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    if params[:id] then
      @profile = Profile.find(params[:id])
    else
      @profile = current_user.profile
    end
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @profile = current_user.profile
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    @profile = current_user.profile
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to '/profile', notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :image, :language, :interest, :gender, :user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def create
        # Create the user from params
        @user = User.new(params[:user])
        if @user.save
          # Deliver the signup email
          UserNotifier.send_signup_email(@user).deliver
          redirect_to(@user.profile, :notice => 'User created')
        else
          render :action => 'new'
        end
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <%= @amount %> dollars!</h2>


<%= link_to 'Home', root_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gdaymateapp</title>
    <%= csrf_meta_tags %>

    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Palanquin" rel="stylesheet">
    <link rel="icon" href="/images/logo.png">
    </head>

  <body>
  <%= render 'navbar/navbar' %>
  
    <%= yield %>
  
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="tour-form">
    <div class="field">
      <%= form.label :title %><br>
      <%= form.text_field :title, id: :listing_title %>
    </div>

    <div class="field">
      <%= form.label :description %><br>
      <%= form.text_area :description, id: :listing_description %>
    </div>

    <div class="field">
      <%= form.label :date %><br>
      <%= form.text_field :date, id: :listing_date %>
    </div>

    <div class="field">
      <%= form.label :cost %><br>
      <%= form.text_field :cost, id: :listing_cost %>
    </div>

    <div class="field">
      Image
      <%= form.file_field :image %>
    </div>

    <div class="field">
    <%= form.label :itinerary %><br>
    <%= form.text_area :itinerary, id: :listing_itinerary %>
    </div>

    <br>
    <div class="actions">
     <%= form.submit %>
    </div>

  <% end %>
</div>

app/views/listings/edit.html.erb
<div class="container">


<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Listings</h1>

<% @listings.each do |listing| %>


    <div class="tour-section">
      <div class ="row tour-title">
          <div class="col-md-6">
            <h1> <%= "Julian Day" %> </h1>
          </div>

          <div class="col-md-6">
            <h1> <%= listing.title %> </h1>
          </div>

      </div>

      <div class="row tour-info">  
          <div class="col-md-6 col-sm-12 tour-image-box">
            <img class="tour-image" src="<%= listing.image %>" alt="user display picture">
          </div>


          <div class="col-md-6 col-sm-12 tour-info-box">
          
              <div>

                <p>Languages: English, Korean</p>
                <p>Interest: Dance</p>
                <p>Date: <%= listing.date %></p>
                <p>Cost: $<%= listing.cost %></p>
                
                  <button type="button" class="btn btn-dark"><%= link_to 'Details', listing %></button>
                

              </div>

          </div>


      </div>

    </div>

    <% end %>



    <div class="new-listing-button">
      <%if user_signed_in? %>
        
        <button type="button" class="btn btn-dark"><%= link_to 'Create New Tour', new_listing_path%></button>
      <% else %>
        <button type="button" class="btn btn-dark"><%= link_to 'Create New Tour', new_user_session_path%></button>
      <% end %>

    </div>

app/views/listings/new.html.erb
<h1>Create New Tour</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<div class="show-box">
  <div class="container">
      <p id="notice"><%= notice %></p>

        <div class="listing m-3">
          <div class="row">
            <div class="col-md-4 col-sm-12">
              <div class="listing-image-section">
                <img src="<%= @listing.image %>" alt="listing image">
              </div>
            </div>

            <div class="col-md-4 col-sm-12 listing-section">
              <p class="listing-title"><%= @listing.title %></p>
              <p class="listing-description"><%= @listing.description %></p>


              <% if((@listing.user) == (current_user))  %>
        
              <button type="button" class="btn btn-dark"><%= link_to 'Edit', edit_listing_path(@listing) %></button>
              <button type="button" class="btn btn-dark"><%= link_to 'Delete', @listing, method: :delete, data: { confirm: 'Are you sure?' } %></button>

              <% end %>
              <button type="button" class="btn btn-dark"><%= link_to 'Back', listings_path %></button>

            </div>

            <div class="col-md-3 col-sm-12 seller-container">
              <div class="seller-box">
                <p class="listing-cost">$<%= @listing.cost %> AUD</p>
                
                <button type="button" class="btn btn-dark">Contact</button>
            <% if(user_signed_in?) then %>
              <%= form_tag charges_path do %>
              <%= hidden_field_tag :listing_id, @listing.id %>
                <article>
                  <% if flash[:error].present? %>
                    <div id="error_explanation">
                      <p><%= flash[:error] %></p>
                    </div>
                  <% end %>
                  
                </article>

                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                        data-description="<%= @listing.title %>"
                        data-amount="<%= @amount %>"
                        data-locale="auto"></script>
              <% end %>

              <% end %>
              </div>
            </div>

          </div>

          <div class="listing-itinerary-box">
            <p class="listing-itinerary-title">Itinerary</p>
            <p class="listing-itinerary"><%= @listing.itinerary %></p>
          </div>

      </div>
    </div>
</div>

app/views/navbar/_navbar.html.erb
<div class="nav-bar">
<nav class="navbar navbar-expand-lg navbar-light ">

<a class="navbar-brand" href="/">G'Day Travel Mate</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">

<form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-light" type="submit">Search</button>
  </form>


  <ul class="navbar-nav ml-auto">

    <li class="nav-item">
      <a class="nav-link" href='/'>Home</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="/#about">About</a>
    </li>

    <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Tours
    </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">

        <%= link_to 'All Tours', listings_path, class: 'dropdown-item' %>
        <%if user_signed_in? %>
        <%= link_to 'My Tours', user_listings_path(current_user), class: 'dropdown-item' %>
        <% else %>
        <%= link_to 'My Tours', new_user_session_path, class: 'dropdown-item' %>
        <% end %>
        <%if user_signed_in? %>
        <%= link_to 'Create a Tour', new_listing_path, class: 'dropdown-item' %>
        <% else %>
        <%= link_to 'Create a Tour', new_user_session_path, class: 'dropdown-item' %>
        <% end %>
      </div>
    </li>

    <li class="nav-item">

    <%if user_signed_in? %>
       <a class="nav-link" href="/profile">My Profile</a>
       <% else %>
       <%= link_to 'My Profile', new_user_session_path, class: 'nav-link' %>
       <% end %>
    </li>



    <li class="nav-item">
      <a class="btn btn-outline-light"    <% if user_signed_in? %>
      <%= link_to("Logout", destroy_user_session_path, :method => :delete) %>
    <% else %>
      <%= link_to 'Login / Sign Up', new_user_session_path %>
    <% end %>
    </li>


   

    


  </ul>
  
</div>
</nav>
</div>

app/views/pages/home.html.erb
<div class="bg-image">
   
    <h1 class="GTM">G'day Travel Mate</h1>

</div>



<br>

<div class="container">
    <div class="about" id="about">


        <h1> 
        About us
        </h1>



    <p class="about-description">
        G’Day mate is a new travel platform!
        <br>
        <br>
         Browse through profiles, choose the adventure and companion that’s right for you!
         <br> 
         With a ‘Mate’ who sets out the right adventure you are able to exchange cultures and connect with someone new!
        <br>
        <br>
         Book an adventure today!
    </p>

    </div>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name, id: :profile_name %>
  </div>



  <div class="field">
  Image
  <%= form.file_field :image %>
  </div>


  <div class="field">
    <%= form.label :language %><br>
    <%= form.text_field :language, id: :profile_language %>
  </div>

  <div class="field">
    <%= form.label :interest %><br>
    <%= form.text_field :interest, id: :profile_interest %>
  </div>

  <div class="field">
    <%= form.label :gender %><br>
    <%= form.text_field :gender, id: :profile_gender %>
  </div>


<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">


<h1>Edit My Profile</h1>

<%= render 'form', profile: @profile %>


<%= link_to 'Back', '/profile' %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Language</th>
      <th>Interest</th>
      <th>Gender</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.image %></td>
        <td><%= profile.language %></td>
        <td><%= profile.interest %></td>
        <td><%= profile.gender %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class="container">

<h1>
My Profile
</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>



<p>
  <strong>Image:</strong>
  <%= image_tag(@profile.image.to_s)%>
</p>


<p>
  <strong>Languages:</strong>
  <%= @profile.language %>
</p>

<p>
  <strong>Interests:</strong>
  <%= @profile.interest %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @profile.gender %>
</p>



<%= link_to 'Edit', edit_profile_path %> 

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>